### PR TITLE
Update wordpress-faq.md

### LINKED ISSUE #4138: Tidy up Wordpress FAQ under Sending Emails in For Developers
## Expected content

For the API Key used for sending emails (the General tab):

– Full Access to Mail Send.
– Read Access to Stats. 
– Read Access to Suppressions > Unsubscribe Groups. 
– Read Access to Template Engine. 

For the API Key used for contact upload (the Subscription Widget tab):

– Full Access to Marketing Campaigns.

There are misaligned list items in [For Developers -> WordPress FAQ](https://sendgrid.com/docs/for-developers/sending-email/wordpress-faq/) which should be properly visible line by line instead of paragraph look and little alignments for texts.

## Actual content

For the API Key used for sending emails (the General tab): – Full Access to Mail Send. – Read Access to Stats. – Read Access to Suppressions > Unsubscribe Groups. – Read Access to Template Engine. For the API Key used for contact upload (the Subscription Widget tab): – Full Access to Marketing Campaigns.

**Link to page**: [For Developers -> WordPress FAQ](https://sendgrid.com/docs/for-developers/sending-email/wordpress-faq/)

### PR DESCRIPTION
**Pull request by ghost**
**Description of the change**: Update Misaligned List Items
**Reason for the change**: Issue #4138 
**Link to original source**: https://github.com/Sendgrid/docs/blob/develop/content/docs/for-developers/sending-email/wordpress-faq.md
Closes #4138

### CODE REVIEW

**Comment by ThiruPraveen18** [comment]
Can you add Hacktoberfest Label? @thinkingserious

**Comment by thinkingserious** [comment]
Hello @ThiruPraveen18,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by thinkingserious** [comment]
Hello @ThiruPraveen18,<br /><br/>Thanks again for the PR!<br /><br />                                         We noticed that you have earned 1 out of the 5 points needed to receive glorious SendGrid Hacktoberfest swag.<br /><br />                                         Please take a moment to checkout <a href="https://dx.sendgrid.com/hacktoberfest/issues">this link</a> to find more issues to get you past the required threshold.<br /><br />                                         Also, please be sure that you have officially registered <a href="https://dx.sendgrid.com/hacktoberfest/join">here</a>.<br /><br />                                         Thank you and Happy Hacktobering!<br /><br />                                         Team SendGrid DX

**Comment by thinkingserious** [comment]
Hello @ThiruPraveen18,<br /><br/>Thanks again for the PR!<br /><br />                                         You have earned 1 out of the 5 points needed to receive glorious SendGrid Hacktoberfest swag.<br /><br />                                         Please take a moment to checkout <a href="https://dx.sendgrid.com/hacktoberfest/issues">this link</a> to find more issues to get you past the required threshold or to simply continue the celebration.<br /><br />                                         Also, <strong>please be sure you have officially registered with us <a href="https://dx.sendgrid.com/hacktoberfest/join">here</a> by November 1, 2018</strong> to qualify.<br /><br />                                         If you have any questions you can email us at <a href="mailto:dx+hacktoberfest2018@sendgrid.com">dx+hacktoberfest2018@sendgrid.com</a>.<br /><br />                                         Thank you and Happy Hacktobering!<br /><br />                                         Team SendGrid

**Pull request merged**
