### PR TITLE
Adding Standard Drivers (ADO.NET, JDBC, ODBC)

### PR DESCRIPTION
**Pull request by JerodJ**

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @JerodJ,<br /><br/>Thank you for the PR!<br />                                              <br />We will be reviewing this PR soon, in the mean                                              time, if you have not, please be sure to                                              <a href="https://github.com/sendgrid/docs#clas-and-cclas">                                             sign our CLA</a> so that we can merge your changes. Thanks again!                                             <br /><br />Team DX

**Comment by JerodJ** [comment]
Just checking in. I sent my signed CLA on 16 December, 2016.

**Comment by thinkingserious** [comment]
Hi @JarodJ,

My apologies, yes we have your CLA on file and a new one is not needed.

We recently updated our process to a new system where you just need to fill out a simple form and click a button :) 

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @JerodJ,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
