### PR TITLE
Added documentation about X-Message-ID

### LINKED ISSUE #2797: mail.send v3 APi documentation doesn't mention X-Message-ID
The documentation at https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html doesn't mention the `X-Message-ID` that's passed back in the returned headers at all. However, SendGrid recommends that users store this data to correlate to their Event Webhook data, and this data is very useful for Support troubleshooting.

### PR DESCRIPTION
**Pull request by sarthak-code**
**Description of the change**: Added documentation about X-Message-ID
**Reason for the change**: [Mentioned in the issue](https://github.com/sendgrid/docs/issues/2797)
**Link to original source**: [Original File](https://github.com/sendgrid/docs/blob/develop/source/API_Reference/Web_API_v3/Mail/index.html) 

Closes #2797 

@ksigler7

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3140) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3140) before we can accept your contribution.<br/><hr/>**Sarthak Agarwal** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/docs?pullRequest=3140) it.</sub>

**Comment by sarthak-code** [comment]
@ksigler7 could you please help me with the cla, I have signed it with the email associated with my github account but it, still states that the CLA hasn`t been signed yet because the email attached is not attached with the github account, even though it is, please help me out, this is my first pr.

image

as you can see,i have signed the pr with the email I use to sign in, I dont know , why is this a problem

**Comment by ksigler7** [comment]
@sarthak-code - that's strange. we're investigating!

**Comment by sarthak-code** [comment]
@ksigler7 I guess I figured it out, shall I close this and open another pr? Also could you please view the code and let me know if any else needs to be added?

**Comment by sarthak-code** [comment]
Sorry for all the confusion, and I highly apologise for the same, I am closing this pr and i have opened a new [one](https://github.com/sendgrid/docs/pull/3150), kindly review it.

Sorry, and Thank you

**Comment by ksigler7** [comment]
@sarthak-code okay, cool! We will review it probably on Monday. Can you tell me what you did to fix the CLA issue? We did not do anything because we couldn't figure out what was wrong.

**Comment by sarthak-code** [comment]
@ksigler7 sorry from my side,it was a very silly mistake .I actually changed my system ,but forgot to set up a public email, and pushed changes from my machine ,so the changes were pushed without any email attached to them, so it showed the grey octocat against my name, Sarthak Agarwal above.

Really Sorry to bother you.

**Pull request closed without merging**
