### PR TITLE
Added Info for Using V2 API in Integrate/Code_Examples/v2_Mail/ (Fixes #2840)

### LINKED ISSUE #2840: Go
https://sendgrid.com/docs/Integrate/Code_Examples/v2_Mail/go.html

the code sample is out-dated. the go wrapper doesn't support API V2 any more...
I wish there were back-ward compatibility though.

### PR DESCRIPTION
**Pull request by SuyashLakhotia**
**Description of the change**: Added information note for using the V2 API in the code examples for  `v2_Mail`. Couldn't add it for Perl since `sendgrid-perl` doesn't seem to have a `TROUBLESHOOTING.md` file. Fixes #2840.

**Reason for the change**: Out-dated pages for code examples.

**Link to original source**: https://github.com/sendgrid/docs/issues/2840

@ksigler7

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/docs?pullRequest=2961) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/docs?pullRequest=2961) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/docs?pullRequest=2961) it.</sub>

**Comment by ksigler7** [comment]
thanks so much @SuyashLakhotia!

**Comment by thinkingserious** [comment]
Hello @SuyashLakhotia,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by SuyashLakhotia** [comment]
@thinkingserious Sweet, thanks! Filled out the form. :)

**Pull request merged**
