### PR TITLE
Addition of X-Message-ID documentation

### LINKED ISSUE #2797: mail.send v3 APi documentation doesn't mention X-Message-ID
The documentation at https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html doesn't mention the `X-Message-ID` that's passed back in the returned headers at all. However, SendGrid recommends that users store this data to correlate to their Event Webhook data, and this data is very useful for Support troubleshooting.

### PR DESCRIPTION
**Pull request by sarthak-code**
**Description of the change**:Added Documentation of X-Message-ID and example response
**Reason for the change**:Mentioned in the [issue](https://github.com/sendgrid/docs/issues/2797)
**Link to original source**:Original [File](https://github.com/sendgrid/docs/blob/develop/source/API_Reference/Web_API_v3/Mail/index.html)

Closes #2797 

@ksigler7

### CODE REVIEW

**Comment by ksigler7** [comment]
thanks again for this @sarthak-code!

**Comment by thinkingserious** [comment]
Hello @sarthak-code,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by sarthak-code** [comment]
Hey Team,
It's been more than a month now that hacktoberfest is gone, and it was a
great one. I am just curious to know how much more time till I get my swag
or even if I could know the shipping details, it would be awesome.

**Comment by ksigler7** [comment]
@sarthak-code - thanks for touching base with us! Did you fill out the form requesting swag? If you filled out the form and included your email address, you should get an email with tracking information once the swag is shipped. We use the same company as Github and DigitalOcean, so it'll work very similarly. The problem that we had is that we were only expecting a small number of contributions and so we ordered only 200 t-shirts. Then we had over 1000 people contribute, so we had to order a lot more t-shirts and they are all on backorder and taking a while. It will also take some extra time to ship anywhere outside of the United States too, as they packages have to go through customs.

We've learned a lot of important lessons here, and we will do better with ordering and communicating all of this next year!

**Pull request merged**
