### PR TITLE
Update instructions for Joomla configuration include SMTP security and port number

### PR DESCRIPTION
**Pull request by manojLondhe**

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3369) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3369) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/docs?pullRequest=3369) it.</sub>

**Comment by ksigler7** [comment]
thanks @manojLondhe!

**Comment by thinkingserious** [comment]
Hello @manojLondhe,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by manojLondhe** [comment]
@ksigler7 thank you for merging :+1:  
@thinkingserious thank you for the swag-form!

**Pull request merged**
