### PR TITLE
add missing bracer

### PR DESCRIPTION
**Pull request by sourcesoft**
**Description of the change**:
Adds a missing bracer

### CODE REVIEW

**Comment by ksigler7** [comment]
@sourcesoft great catch! thanks for the update

**Comment by thinkingserious** [comment]
Hello @sourcesoft,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by sourcesoft** [comment]
Thank you. I submitted the form too.

**Comment by ksigler7** [comment]
@sourcesoft awesome! thanks again

**Pull request merged**
