### PR TITLE
Updated "Delivery Metrics" to "Statistics"

### PR DESCRIPTION
**Pull request by prnvdixit**
Changed all instances of "Delivery Metrics" to "Statistics"
as SendGrid is no longer using the term "Delivery Metrics"
and is using "Statistics" instead.

Fixes https://github.com/sendgrid/docs/issues/2965

**Description of the change**:
**Reason for the change**:
**Link to original source**:

@ksigler7

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3028) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3028) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/docs?pullRequest=3028) it.</sub>

**Comment by prnvdixit** [comment]
@ksigler7 @thinkingserious @Whatthefoxsays I have left out editing some of the URLs containing "Delivery Metrics" as after editing they were all either leading to "Bad Gateway Error" or were redirecting to "Statistics/index.html". (I have fixed all other URLs) :smile:
Also, since the issue is still assigned to me - Let me know if the "left out" URLs need to be edited too, Would be happy to fix them.  :+1:

**Comment by ksigler7** [comment]
@prnvdixit thanks for the updates! we got a huge amount of pull requests last night, so it may be a little while before we can take a look at this, but we will for sure get back to you

**Comment by prnvdixit** [comment]
@ksigler7 Yeah, I understand the rush. :+1:

**Comment by ksigler7** [comment]
@prnvdixit this looks perfect! I don't think we need a second pull request right now, but please feel free to check back often for other open issues. thanks for your work on this!

**Comment by thinkingserious** [comment]
Hello @prnvdixit,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by prnvdixit** [comment]
@ksigler7 Yeah - Definitely. I am all in for helping in development of the project :smile:. Thanks for the quick review and merge anyway. :+1:

**Pull request merged**
