### PR TITLE
Fixes 'validation' spelling

### PR DESCRIPTION
**Pull request by laniehei**
**Description of the change**:
Fixes 'validation' spelling

**Reason for the change**:
Misspelling

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/docs?pullRequest=5664) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/docs?pullRequest=5664) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/docs?pullRequest=5664) it.</sub>

**Comment by Whatthefoxsays** [comment]
Thank you for your contribution @laniehei! Can you please sign our [CLA](https://cla.sendgrid.com/sendgrid/docs?pullRequest=5664) so I can merge in your PR?

**Comment by laniehei** [comment]
@Whatthefoxsays I have signed it! 😊

**Comment by thinkingserious** [comment]
Hello @laniehei,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by laniehei** [comment]
@thinkingserious @Whatthefoxsays sweet! I'm excited -- thank you (: 

On another note, I think the email validation API is returning a 200 (as expected) but the docs say it'll return a 201. (see here: https://sendgrid.api-docs.io/v3.0/email-address-validation/validate-an-email)

where should I go to open an issue on this?

**Pull request merged**
