### PR TITLE
simple fix for dom xss in apidocs_iframe func

### PR DESCRIPTION
**Pull request by wreet**
* * fix an issue where the url hash is used without sanitization in apidocs_iframe

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3465) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3465) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/docs?pullRequest=3465) it.</sub>

**Comment by ksigler7** [comment]
@wreet - thanks again for taking the time to fix this! Merging it into develop now, and then it will get pushed to production on Friday with our regular weekly release. Do you want me to go in and comment on the jira issue when this gets pushed to production?

**Comment by thinkingserious** [comment]
Hello @wreet,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by wreet** [comment]
@ksigler7 yeah, that would be great!

**Pull request merged**
