### PR TITLE
add free version of comoon.ttf font

### LINKED ISSUE #4211: 404 not found the font  'icomoon.ttf'
## Expected content
this error should not come 

## Actual content

**Link to page**:
screenshot from 2018-10-13 20-41-31

### PR DESCRIPTION
**Pull request by inyee786**
**Description of the change**:
comoon.ttf is use for icons

**Reason for the change**:
the doc doesn't have the comoon.ttf file, and so it can't able to fetch the font

Signed-off-by: inyee786 <intakhab.cusat@gmail.com>

**Link to original source**:

fixes :#https://github.com/sendgrid/docs/issues/4211

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/docs?pullRequest=4212) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/docs?pullRequest=4212) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/docs?pullRequest=4212) it.</sub>

**Comment by ksigler7** [comment]
sorry, I miss marked this one

**Comment by thinkingserious** [comment]
Hello @inyee786,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by thinkingserious** [comment]
Hello @inyee786,<br /><br/>Thanks again for the PR!<br /><br />                                         We noticed that you have earned 4 out of the 5 points needed to receive glorious SendGrid Hacktoberfest swag.<br /><br />                                         Please take a moment to checkout <a href="https://dx.sendgrid.com/hacktoberfest/issues">this link</a> to find more issues to get you past the required threshold.<br /><br />                                         Also, please be sure that you have officially registered <a href="https://dx.sendgrid.com/hacktoberfest/join">here</a>.<br /><br />                                         Thank you and Happy Hacktobering!<br /><br />                                         Team SendGrid DX

**Pull request merged**
