### PR TITLE
Remove or fix link

### PR DESCRIPTION
**Pull request by cemurray**
Landing page is broken. Cannot find correct page.

**Description of the change**: Removed link
**Reason for the change**: Landing page broken. 
**Link to original source**: https://sendgrid.com/docs/User_Guide/User_Guide/Marketing_Campaigns/getting_started.html

@ksigler7

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/docs?pullRequest=2790) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/docs?pullRequest=2790) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/docs?pullRequest=2790) it.</sub>

**Comment by ksigler7** [comment]
@cemurray Thanks for the fix Christine!!! Just so you know, this page is under construction, and that data is getting added back in soon.

Do you mind adding your full name and a picture to your github profile too?

**Comment by thinkingserious** [comment]
Hello @cemurray,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by cemurray** [comment]
No problem @ksigler7! I thought I added my full name....do you want my middle name too? I'll add a photo now.

**Comment by ksigler7** [comment]
@cemurray haha, no need for your middle name. I think I must have clicked your profile right before you added your full name, so I didn't see it. Everything looks good now!

Thanks again for the update! I have a docs contributor pin for you, I keep them at my desk!

**Pull request merged**
