### PR TITLE
Send MIME messages with SendGrid

### LINKED ISSUE #4233: How to Send MIME messages with SendGrid
Explain how MIME messages can be sent, in more detail, using SendGrid. Explain that this can only be done over SMTP.

The doc should go here: 
for-developers/sending-email/__________/

### PR DESCRIPTION
**Pull request by rahulpuroht**
**Description of the change**:
MIME messages can be sent, in more detail, using SendGrid.
**Link to original source**:

Closes #4233

### CODE REVIEW

**Comment by ksigler7** [comment]
hi @rahulpuroht - thanks for this PR! this is breaking our build because it's missing any of the md headmatter. For a good example of the headmatter, see this page: https://github.com/sendgrid/docs/edit/develop/content/docs/for-developers/parsing-email/inbound-email.md

Also, please make sure you're following [our styleguide](https://github.com/sendgrid/docs/blob/develop/styleguide.md) for both of your PRs

**Comment by rahulpuroht** [comment]
Done with head-matter .Please update if required any other actions.Thanks

**Comment by thinkingserious** [comment]
Hello @rahulpuroht,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by ksigler7** [comment]
@rahulpuroht - thanks! I've given you the hacktoberfest credit, and I plan to do another in-depth review on this later today

**Comment by thinkingserious** [comment]
Hello @rahulpuroht,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
