### PR TITLE
fixing a wrong git command

### PR DESCRIPTION
**Pull request by PAPERPANKS**
**Description of the change**: writing a correct git command
**Reason for the change**: to fix a wrong git command
**Link to original source**: [here](https://github.com/PAPERPANKS/docs/blob/develop/README.markdown)

in reference to #3134 and #3180 

@ksigler7

### CODE REVIEW

**Comment by PAPERPANKS** [comment]
- Original command doesn't work


docs-1

- See the output for the confirmation 


docs-2

**Comment by PAPERPANKS** [comment]
@ksigler7 this commit [updating email address](https://github.com/sendgrid/docs/pull/3206/commits/85181c5f86aa2015a66aecebdd1f6eeaa5b74224) is in reference to issue #3180 and to #3182 where you requested updates in `source/API_Reference/SMTP_API/index.html ` and other files

**Comment by thinkingserious** [comment]
Hello @PAPERPANKS,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/announcing-hacktoberfest-2017">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by PAPERPANKS** [comment]
@ksigler7 the commit [updating email address](https://github.com/sendgrid/docs/pull/3206/commits/85181c5f86aa2015a66aecebdd1f6eeaa5b74224) is resolving the issue #3180 with `difficulty:medium` tag.
Therefore you should give me `2` more points for this.
[Here](https://dx.sendgrid.com/hacktoberfest) you can check the points should be 6 but 4, please add `difficult:medium` tag to [this](https://github.com/sendgrid/docs/pull/3206/commits/85181c5f86aa2015a66aecebdd1f6eeaa5b74224) commit

**Comment by PAPERPANKS** [comment]
@ksigler can you just help me with the above comment asap

**Pull request merged**
