### PR TITLE
Fixed Drag & Drop Module Descriptions and Styles hyperlink 

### LINKED ISSUE #3192: In-page links may not be correct on 'design editor' page
The in-page link for `Drag and Drop Code Examples` is not correct when linked within this page.

It should be: `#-Drag--Drop-Code-Examples` Not `#-Drag-&-Drop-Code-Examples`

Please fix this link and check the other in-page links from the web to make sure they are working properly. 

**Link to page**:
https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/design_editor.html

### PR DESCRIPTION
**Pull request by ng29**
**Description of the change**: Fixed Drag & Drop Module Descriptions and Styles hyperlink 
**Reason for the change**: The hyperlink was not working properly
**Link to original source**:[link](https://github.com/sendgrid/docs/blob/develop/source/User_Guide/Marketing_Campaigns/design_editor.md)

Closes #3192 

@ksigler7

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3193) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3193) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/docs?pullRequest=3193) it.</sub>

**Comment by thinkingserious** [comment]
Hello @ng29,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by ng29** [comment]
hey team,

Its been a great pleasure contributing in this month of hacktoberfest to
Send grid also , and like all i am also waiting for my tshirt , hacker pin
and sticker.
I wanna ask that whether my package is shipped or not as its been more than
2 weeks and i have not recieved any mail regarding shipping details.
So kindly check it out :)

Thanks

**Comment by ksigler7** [comment]
@ng29 - sorry for the delay in shipping the swag! I believe that everyones stuff is being shipped out together very soon. Our systems got overwhelmed because we had such an amazing response to hacktoberfest - thanks for checking back about it though! Here's more information: https://github.com/sendgrid/docs/issues/3290

**Comment by ng29** [comment]
oh.. no worries .
waiting for my swag :)
Just ping me the details when package is shipped

Thanks

**Comment by ng29** [comment]
hey team,

I wanna ask that whether swag for the hacktoberfest is shipped or not as it
is taking too long  for the same and also no tracking details are recieved
too.
Kindly look into it

Thanks

**Comment by ksigler7** [comment]
@ng29 - right now, our t-shirts are on backorder. This happened because we ended up getting way more contributions than we expected, and we apologize for the inconvenience - we definitely want to take care of our contributors! We will for sure let you know when we are able to make the shipment, which should be soon.

**Comment by ng29** [comment]
Okay cool. .
No issues..
Waiting for the package :(

Thanks

**Comment by mbernier** [comment]
@ng29 I got you! ... I think we've been talking on Twitter?

It's happening, it's just taking a bit bc the response to our issues was so great. we were prepared for about 100 PRs, we got 1000. So... we're scrambling and will get you hooked up as soon as we can. The fulfillment group has our order and they are sending things out as fast as they can too! 

Thank you for following up

**Comment by ng29** [comment]
yep matt..
ohh man such a huge difference in the numbers.. cool stuff :)
okay cool no problem. just waiting mate :)

Thanks

**Comment by ng29** [comment]
hey team,

Its been too long and no information about the package .?
I wanna know that when package will be shipped ? and do send shipping
details when done .

Thanks

**Comment by ng29** [comment]
hey team ,

How much we have to wait for the swag :(
Its next october coming so fast :(

**Comment by ksigler7** [comment]
@ng29 - we messed up our order and the last batch of swag is going out now. We can't do anything to fix this year, but next year, count on the fact that we have learned a ton of lessons from this and will have a much better system in place.

**Comment by ng29** [comment]
ooohhhh.... glad to hear that swag is ready for shipping :)
Excited :)

**Comment by ng29** [comment]
hey ,
Still i had not received my swag , its been too long , dont wanna loose my package :(

**Comment by ksigler7** [comment]
Hey @ng29 - I am checking your individual shipment and I will follow up with you by email

**Pull request merged**
