### PR TITLE
Update SiteConfig.js

### PR DESCRIPTION
**Pull request by mrprit**
**Description of the change**:
**Reason for the change**:
**Link to original source**:

Closes #

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/docs?pullRequest=4342) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/docs?pullRequest=4342) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/docs?pullRequest=4342) it.</sub>

**Comment by pushkyn** [comment]
These changes do not make sense

**Comment by ksigler7** [comment]
Please check out our open issues for changes that we’re looking for in this repo! We’re adding new ones from easy to difficult every day.

**Comment by ksigler7** [comment]
@pushkyn - I've really appreciated all of your reviews!

**Pull request closed without merging**
