### PR TITLE
Fix url_offset typo

### PR DESCRIPTION
**Pull request by int-ua**

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/docs?pullRequest=5398) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/docs?pullRequest=5398) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/docs?pullRequest=5398) it.</sub>

**Comment by int-ua** [comment]
I believe this smallest possible change does not require reading CLA.

**Comment by Whatthefoxsays** [comment]
Hi @int-ua! Thanks for your contribution! Unfortunately, I can't merge anything in until the contributor has signed the CLA. Can you please take some time to do so?

**Comment by int-ua** [comment]
I understand that you have policy and I don't need credit for this so I'll just close this PR and hope you will fix it. Also please check "Obvious fix" policy in rabbitmq repos: https://github.com/rabbitmq/rabbitmq-website/pull/777

**Pull request closed without merging**
