### PR TITLE
Invalid email explanation summary

### PR DESCRIPTION
**Pull request by hmbrown64**
Added summary of what an invalid email is and link to glossary.

**Description of the change**:
**Reason for the change**:
**Link to original source**:

Closes #

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @hmbrown64,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by ksigler7** [comment]
this looks great @hmbrown64! I'm not sure what's wrong with the build, so troubleshooting that now

**Comment by dagolinuxoid** [comment]
> this looks great @hmbrown64! I'm not sure what's wrong with the build, so troubleshooting that now

 @ksigler7, she made a tiny but crucial mistake instead of `{{root_url}}/docs/glossary/invalid-email/` should be just `{{root_url}}/glossary/invalid-email/`. I am 100% sure that `root_url` stands for `sendgrid.com/docs`. Am I correct?

**Comment by ksigler7** [comment]
@dagolinuxoid - thank you so much for this!!!!

**Pull request closed without merging**
