### PR TITLE
Templates re-org part deux

### PR DESCRIPTION
**Pull request by Whatthefoxsays**
- [x] Taken all valuable information from existing pages and added it to the new category
- [x] Deleted old pages
- [x] Deleted old images from images folder
- [x] Added remaining images to the img folder
~~- [ ] Screenshots updated~~
~~- [ ] all images have an alt tag~~
- [x] all images are named according to style guide
- [x] Updated the glossary
- [x] Added redirects from deleted page to new content
- [x] Head data should have SEO title, keywords, and description
- [x] Content is in Jobs-to-be-done format
- [x] Update all in-content links and links to deleted pages
- [x] Added additional resources (aim for a link to the glossary, the blog and other jobs-to-be-done)
- [x] Added a TOC
~~- [ ] Added a talk to Dewey/Olivia section~~
- [x] title optimized for google search snippits
- [x] content optimized for google search snippits
- [x] keyword optimization for each category
- [x] addressed/closed any related issues in the backlog
- [x] pages are have the correct weight
- [x] content has been run through grammarly
~~- [ ] properly trademarked names for any product names outside of SendGrid~~

### CODE REVIEW

**Comment by Whatthefoxsays** [comment]
Please also review the following pages:

http://localhost:4000/User_Guide/Transactional_Templates/using_handlebars.html

http://localhost:4000/User_Guide/Transactional_Templates/migrating_from_legacy_templates.html

**Comment by ksigler7** [comment]
In using_handlebars.md, the helpers should be in code syntax ` `` `

**Comment by ksigler7** [comment]
On the migrating_from_legacy_templates.md page, add a note about how you should search and replace and give the proper handlebars syntax for if the automatic migrator doesn't work

**Comment by ksigler7** [comment]
Oh, the third one is the one I had to rename (remember, it had to match what we gave the team to link to in the UI), so now it's here - http://localhost:4000/User_Guide/Transactional_Templates/create_and_edit_transactional_templates.html

**Comment by thinkingserious** [comment]
Hello @Whatthefoxsays,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
