### PR TITLE
Update applemail.md

### LINKED ISSUE #3210: Update Apple Mail Integration Instructions with current iOS
## To do:

Update the Apple Mail integration page with updated iOS information, steps, and screen shots. 

**Link to page**: https://sendgrid.com/docs/Integrate/Mail_Clients/applemail.html

### PR DESCRIPTION
**Pull request by cs2425**
**Description of the change**: I changed the steps to integrate SendGrid into Apple Mail to reflect OS Sierra. Screenshots below in order:
newapplemail_step_1
newapplemail_step_2
newapplemail_step_3
newapplemail_step_4
**Reason for the change**: Issue #3210 for hacktoberfest 
**Link to original source**: https://github.com/sendgrid/docs/blob/develop/source/Integrate/Mail_Clients/applemail.md

Closes #3210 

@ksigler7

### CODE REVIEW

**Comment by ksigler7** [comment]
hey @cs2425 - thanks so much for these updates! The build is currently failing, and it's because you need to add these new images into the build. Here's how to do that:

Navigate to [your fork > the patch-2 branch > then to the source>images folder](https://github.com/cs2425/docs/tree/patch-2/source/images), then click [Create new file] and follow the prompts to add these new images into that folder. 
image
As long as you are on that branch, adding the images should automatically update this pull request! Thanks so much!

**Comment by cs2425** [comment]
@ksigler7 thanks for letting me know! They are uploaded to patch-2 now. Let me know if I need to do something else, thanks!

**Comment by ksigler7** [comment]
@cs2425 thanks so much! I tweaked the links in the file to match the names of the ones you added, but other than that, this looks great!

**Comment by thinkingserious** [comment]
Hello @cs2425,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/announcing-hacktoberfest-2017">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
