### PR TITLE
Add release note and remove orig. IP from table

### PR DESCRIPTION
**Pull request by astuteape**
**Description of the change**: These docs updates are required to reflect the removal of the originating IP from the received email header.

### CODE REVIEW

**Comment by Jericho** [comment]
Does this mean that `originating_ip` is no longer available when searching for email activities?

If so, the [documentation about searching for email activities](https://sendgrid.com/docs/for-developers/sending-email/getting-started-email-activity-api/#query-reference) should be updated  .

**Comment by astuteape** [comment]
Hi @Jericho, thanks for the note. This PR will remove the originating IP from the table on that docs page. Is there somewhere else we missed? This PR is still being updated, so I'm happy to include updates I may have missed. Thanks again for the note.

**Comment by Jericho** [comment]
You're welcome. However, can you please confirm whether this mean that `originating_ip` is no longer available when searching for email activities?

Also, when will this change go live? To be clear: I'm asking about the change in the API.

**Comment by astuteape** [comment]
This does mean the `originating_ip` will no longer be available in email activities. These changes are expected within the next several weeks.

**Pull request merged**
