### PR TITLE
Added IP Pool info to the event web hook page

### PR DESCRIPTION
**Pull request by johnvajda**

### CODE REVIEW

**Comment by mbernier** [comment]
Looks like the build script had a problem with the JSON in this change. If you can't get it in less than 3 minutes, I'll run a build locally and see if I can figure it out.

**Comment by eexit** [comment]
This one's very expected, would be nice to have it merged soon :)

**Comment by eexit** [comment]
By the way, the pool IP option is mostly forgotten in almost all SG SMTP-API SDK, here, I added it for the [PHP SDK](https://github.com/sendgrid/smtpapi-php/pull/5)

**Comment by mbernier** [comment]
JSON is fine now, thanks @johnvajda -- merging

**Pull request merged**
