### PR TITLE
Fixed more typos throughout docs

### PR DESCRIPTION
**Pull request by lierluis**
**Description of the change**: Fixed a few more typos
**Reason for the change**: Might as well continue
**Link to original source**: #3037

@ksigler7

### CODE REVIEW

**Comment by ksigler7** [comment]
@lierluis - I will validate and merge this first thing tomorrow, but I just want to let you know you are awesome and you have inspired this: https://github.com/sendgrid/docs/issues/3053

**Comment by lierluis** [comment]
@ksigler7 wow, I actually made a difference 😮 Not sure if typos are that big of a deal though, I was just doing this for Hacktoberfest, and fixing someone else's work is a lot easier than creating something from scratch... I wouldn't worry too much about all of this and I hope I haven't made you paranoid lol

**Comment by ksigler7** [comment]
@lierluis you have definitely made a difference!! Paranoid is the wrong word - more like aware that there was a bigger problem than we realized. We really appreciate that you've done all of this!

**Comment by thinkingserious** [comment]
Hello @lierluis,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/announcing-hacktoberfest-2017">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
