### PR TITLE
Update event.md

### PR DESCRIPTION
**Pull request by paoga87**
This is an updated example file that was provided to me by one of SendGrid's support engineers a couple of days ago while implementing webhooks. I figured it would be good to update on the documentation as well.

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @paoga87,<br /><br/>Thank you for the PR!<br />                                              <br />We will be reviewing this PR soon, in the mean                                              time, if you have not, please be sure to                                              <a href="https://github.com/sendgrid/docs#clas-and-cclas">                                             sign our CLA</a> so that we can merge your changes. Thanks again!                                             <br /><br />Team DX

**Comment by paoga87** [comment]
@thinkingserious thank you.
I have signed and submitted the CLA paperwork.

Thanks again,
Paola G.

**Comment by eschallock** [comment]
@paoga87 Thanks for the PR here! Any chance you remember who the Support agent was that you worked with on this? I'd love to follow up with them.

**Comment by paoga87** [comment]
@eschallock Sure, his name was Kyle Roberts. He was great!

**Comment by eschallock** [comment]
@paoga87 Awesome, thanks! I'll get this merged in as soon as I can.

**Comment by paoga87** [comment]
@eschallock thanks a lot!

**Pull request merged**
