### PR TITLE
Update GET all IPs endpoint and add new GET assigned ips

### PR DESCRIPTION
**Pull request by jovel**
https://jira.sendgrid.net/browse/SR-1618

### CODE REVIEW

**Comment by brandonmwest** [comment]
Looks good to me!

**Comment by jovel** [comment]
@brandonmwest thanks, will let you guys know once everything is up in prod.

**Comment by johnvajda** [comment]
This change is done, when will the docs update occur?

**Comment by johnvajda** [comment]
Merged this docs change in as this is completed

**Pull request merged**
