### PR TITLE
Escape HTML tags in plain_text_emails_converted_to_html.md

### LINKED ISSUE #2729: Plain text emails converted to HTML
https://sendgrid.com/docs/Classroom/Build/Format_Content/plain_text_emails_converted_to_html.html

You have unescaped HTML tags in your docs.

### PR DESCRIPTION
**Pull request by SLaks**
**Description of the change**: Wrap HTML tags in Markdown code blocks
**Reason for the change**: They were rendering as tags, which was horrible

@ksigler7

Fixes #2729

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/docs?pullRequest=2730) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/docs?pullRequest=2730) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/docs?pullRequest=2730) it.</sub>

**Comment by ksigler7** [comment]
hey @SLaks, that does look bad, so thanks for the catch, and thanks for the fix! If you can go ahead and sign the CLA, I can merge this right away.

**Comment by ksigler7** [comment]
@SLaks I'd love to be able to merge this. Can you please sign the CLA?

**Comment by SLaks** [comment]
I have been instructed that I am not able to sign the SendGrid CLA in its present form.

**Comment by mbernier** [comment]
Hey, @SLaks -

We are currently talking to your legal team to figure out what we can do. Sorry about this!

**Comment by ksigler7** [comment]
Hey @SLaks - thanks again for this pull request. I am going to close this for now, since it's been sitting here for more than 90 days. If our legal team does work things out, we can reopen it.

**Pull request closed without merging**
