### PR TITLE
Custom SSL configurations for click and open tracking

### PR DESCRIPTION
**Pull request by szemek**
This pull request documents possible workaround when using click and open tracking. It is possible to validate DNS record and later configure proxy with SSL certificate.

@ksigler7

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3196) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3196) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/docs?pullRequest=3196) it.</sub>

**Comment by ksigler7** [comment]
@szemek - thanks so much for submitting this! We are in the process of reviewing this content and will hopefully merge it soon - I just want some other folks to take a look at it first.

**Comment by thinkingserious** [comment]
Hello @szemek,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by szemek** [comment]
@ksigler7 thanks for tweaking my changes :) 
@thinkingserious thanks! I filled and sent it (probably twice, so ignore superfluous requests).

**Pull request merged**
