### PR TITLE
Glossary Entry on Deferrals

### PR DESCRIPTION
**Pull request by hmbrown64**
Adjusted deferral macro for glossary post

**Description of the change**:
**Reason for the change**:
**Link to original source**:

@ksigler7

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/docs?pullRequest=2842) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/docs?pullRequest=2842) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/docs?pullRequest=2842) it.</sub>

**Comment by hmbrown64** [comment]
Completed for https://github.com/sendgrid/docs/issues/2751

**Comment by ksigler7** [comment]
@hmbrown64 - for this one, we also need to add an entry on the main glossary [index page](https://github.com/sendgrid/docs/blob/develop/source/Glossary/index.html), so that it shows up [here](https://sendgrid.com/docs/Glossary/index.html)

**Comment by hmbrown64** [comment]
Added link to Glossary index: https://github.com/sendgrid/docs/pull/2888

**Comment by thinkingserious** [comment]
Hello @hmbrown64,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
