### PR TITLE
Add Authorization Note

### PR DESCRIPTION
**Pull request by jacobmovingfwd**
Wording is kinda iffy, but we need to note that most of these calls need the full user:pass Authorization, and don't allow using API Keys.

**Description of the change**:
**Reason for the change**:
**Link to original source**:

Closes #

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @jacobmovingfwd,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Comment by emilyruppe** [comment]
@ksigler7 @jacobmovingfwd so we don't forbid API key authentication on the User endpoints, we just require that the API key have the user scopes, which are not given to API keys by default with the "admin api key" configuration. (Because we don't want to give all API keys power over the user details.) But the call to give the API key User scopes *does* require basic authentication from the parent.  If that's confusing, let me know and I can add more context. Not sure how much of that we want to actually add to the doc.

**Comment by jacobmovingfwd** [comment]
i'd add that, so that we"re saying "use user:pass, or an APi key with [user
scopes]"

**Comment by ksigler7** [comment]
@jacobmovingfwd not sure what you mean here - what's the full text of what you would add?

**Comment by jacobmovingfwd** [comment]
> These API calls require Authorization with an API Key that [has User scopes](https://sendgrid.com/docs/API_Reference/Web_API_v3/API_Keys/api_key_permissions_list.html#User-Settings), or `Basic` Authorization with the Base64-encoded `username:password` of the account.

Unless we have a rule against educating about Basic auth, in which case just the first part.

**Comment by ksigler7** [comment]
see updates there ^^^

**Pull request merged**
