### PR TITLE
Added limitation of only 15 conditions per search

### PR DESCRIPTION
**Pull request by hmbrown64**
Added:

{% info %}
You can search for up to 15 different conditions per request.
{% endinfo %}

Under Search with conditions [POST]

**Description of the change**:
**Reason for the change**:
**Link to original source**:

@ksigler7

### CODE REVIEW

**Comment by ksigler7** [comment]
@hmbrown64 thanks so much for this! This is a great catch. It turns out that 15 is the max for the GET Search with conditions, and the POST Create a Segment too. Do you mind also adding in the same note for the GET and something similar for the POST?

**Comment by hmbrown64** [comment]
added requested change in #2964. I did not see a GET Search with conditions option, only Search with conditions - POST

**Comment by ksigler7** [comment]
thanks lady!!!

**Comment by thinkingserious** [comment]
Hello @hmbrown64,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/announcing-hacktoberfest-2017">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
