### PR TITLE
removed a random alphanumeric string

### PR DESCRIPTION
**Pull request by hseitz**
**Description of the change**: Removed a random alphanumeric string
**Reason for the change**: There appeared to be a random alphanumeric string in the middle of the CDN documentation page. I don't see a reason why it should be there and it looks to me like it could be in error.
**Link to original source**: https://github.com/sendgrid/docs/blame/develop/source/Classroom/Build/Add_Content/content_delivery_networks.md#L68

@ksigler7

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/docs?pullRequest=2713) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/docs?pullRequest=2713) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/docs?pullRequest=2713) it.</sub>

**Comment by ksigler7** [comment]
@hseitz thanks for fixing this! looks like a leftover string from a merge conflict.

**Comment by thinkingserious** [comment]
Hello @hseitz,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by hseitz** [comment]
@thinkingserious will do, the link isn't working currently (504) but I've got some other proposed changes on the way so I'll check back later :D

**Pull request merged**
