### PR TITLE
Additional Resources add to select User Guide pages

### PR DESCRIPTION
**Pull request by Aonepathan**
Added Additional Resources to User Guide pages:

- Email Activity
- Dashboard
- all of SendGrid for Mobile

**Description of the change**: Added a Additional Resources section to above User Guide pages
**Reason for the change**: Relates to Issue #3089 

@ksigler7

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3200) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3200) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Aonepathan<br/>:x: Abdullah Pathan<br/><hr/>**Abdullah Pathan** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/docs?pullRequest=3200) it.</sub>

**Comment by Aonepathan** [comment]
I've accidentally committed from a different computer which now conflicts with the CLA since the user (me) does not have a github account... I reverted the commit but I believe the CLA still is looking at the Abdullah Pathan commit, could the CLA comment be removed or asked again after the revert? This could fix the CLA conflict... you guys know best, lemme know how to fix, sorry!

**Comment by ksigler7** [comment]
@Aonepathan - hmm, I would have guessed that a `git revert` would have worked too. Maybe try a hard reset like suggested here: https://stackoverflow.com/questions/927358/how-to-undo-the-last-commits-in-git

**Comment by Aonepathan** [comment]
@ksigler7 Yikes, I have tried git hard reset, soft reset, amend, revert, and even changed the author of that commit but it doesn't change this pull request historically. I think since the wrong commit was made in the beginning and before the CLA, it's just part of the history, it's gone, just historically it exists. I'll wipe out this pull request and make a new one in hopes it'll work!

**Comment by ksigler7** [comment]
thanks so much @Aonepathan! Sorry for all of the troubles this caused you

**Comment by ksigler7** [comment]
You did a really through and thoughtful job at this - really appreciate it!

**Comment by thinkingserious** [comment]
Hello @Aonepathan,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/announcing-hacktoberfest-2017">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
