### PR TITLE
Update screenshot - issue #2745 

### PR DESCRIPTION
**Pull request by ecodonohoe**
Screenshot, bouncefwd.png, updated in docs/source/images/ to reflect current view on the 
Mail Settings -- Forward Bounce page,

Original issue:  #2745

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/docs?pullRequest=2944) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/docs?pullRequest=2944) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/docs?pullRequest=2944) it.</sub>

**Comment by thinkingserious** [comment]
Hello @ecodonohoe,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by ecodonohoe** [comment]
Hi guys,
I know these generally take some time to arrive (Other Hacktoberfest swag
only arrived after Christmas) but just curious if this stuff is likely to
arrive soon?
Thanks a mil,
Eoin

**Comment by ksigler7** [comment]
Hey @ecodonohoe - things are going really slow. We're working closely with our distributors to get the last wave of swag out now. We've learned a lot from this, and will for sure do much better next year!

**Comment by ecodonohoe** [comment]
No worries Kaylyn, just thought I'd double check. Thanks for your response.

Eoin

**Pull request merged**
