### PR TITLE
Update and rename license to LICENSE

### PR DESCRIPTION
**Pull request by KrishMunot**

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @KrishMunot,<br /><br/>Thank you for the PR!<br />                                              <br />We will be reviewing this PR soon, in the mean                                              time, if you have not, please be sure to                                              <a href="https://github.com/sendgrid/docs#clas-and-cclas">                                             sign our CLA</a> so that we can merge your changes. Thanks again!                                             <br /><br />Team DX

**Comment by ksigler7** [comment]
Hey @KrishMunot , thanks so much for your contribution! Unfortunately, since you haven't signed our CLI, we're not going to be able to merge this pull request at this time.  Since this has been sitting here a while, I am going to go ahead and close this pull request, but feel free to open it again in the future if you sign the CLI!

**Comment by KrishMunot** [comment]
@ksigler7 @thinkingserious Thanks for the comments! I found the entire CLI process a bit cumbersome, as developers and being in 2017, it seems like too much work with the current CLI process. I've signed several other CLI's of other companies before which were much easier and mostly just a quick online form or an automated process. Just a suggestion to improve that process. :)

**Comment by ksigler7** [comment]
@KrishMunot thanks for the feedback!

**Pull request closed without merging**
