### PR TITLE
removes merge markers

### PR DESCRIPTION
**Pull request by dabutvin**

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @dabutvin,<br /><br/>Thank you for the PR!<br />                                              <br />We will be reviewing this PR soon, in the mean                                              time, if you have not, please be sure to                                              <a href="https://github.com/sendgrid/docs#clas-and-cclas">                                             sign our CLA</a> so that we can merge your changes. Thanks again!                                             <br /><br />Team DX

**Comment by eschallock** [comment]
Hey @dabutvin, thank you for the pull request! Unfortunately, I need to get this page fixed as soon as possible, so I'll go ahead and close your PR since we don't yet have your signed CLA. I'll make the fix in a separate PR.

As a token of our sincere appreciation, can we offer you some [free swag](https://docs.google.com/forms/d/e/1FAIpQLSelP4uF-wGJebxVYq1DYw5WzHomEUauab3YiqrshyCkRs0fqw/viewform#start=invite)?

**Comment by eschallock** [comment]
This issue is resolved by https://github.com/sendgrid/docs/pull/2513

**Comment by dabutvin** [comment]
:)

**Pull request closed without merging**
