### PR TITLE
adding logos to readme.md

### PR DESCRIPTION
**Pull request by PAPERPANKS**
**Adding logos and license section in `README file`**

In reference to issue #3134 

@ksigler7

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3171) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3171) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/docs?pullRequest=3171) it.</sub>

**Comment by PAPERPANKS** [comment]
`my-fisrt-pr` please let me know if I forget to add something more

**Comment by ksigler7** [comment]
@PAPERPANKS congrats on your first PR! You did a great job - we appreciate it!

**Comment by thinkingserious** [comment]
Hello @PAPERPANKS,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
