### PR TITLE
Proofread the docs/source/User_Guide/Transactional_Templates/create_edit.md document

### LINKED ISSUE #3208: Fix typos in transactional template documentation
## To do:

Fix typos and broken markdown on [this page](https://sendgrid.com/docs/User_Guide/Transactional_Templates/create_edit.html).

### PR DESCRIPTION
**Pull request by afischer12**
**Description of the change**: Fixed a typo and a few grammatical mistakes
**Reason for the change**: An issue asking for people to proofread this document
**Link to original source**: https://github.com/sendgrid/docs/blob/develop/source/User_Guide/Transactional_Templates/create_edit.md

Closes #3208 

@ksigler7

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3221) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3221) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/docs?pullRequest=3221) it.</sub>

**Comment by ksigler7** [comment]
this looks really good @afischer12, thanks so much! I can merge it when you sign the CLA.

**Comment by afischer12** [comment]
signed it!

**Comment by thinkingserious** [comment]
Hello @afischer12,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
