### PR TITLE
callout for email insight & kotlin code sample

### PR DESCRIPTION
**Pull request by wdharmana**
**Description of the change**: Add Kotlin sample code to documentation with Java Library. Add callout about Email Insight Service.
**Reason for the change**: Kotlin is alternative of Java. Send grid also has Email Insight Service.
**Link to original source**: https://github.com/sendgrid/docs/issues/4577

- [x] Geographic Statistics
- [x] Global Statistics 
- [x] Google Analytics and SendGrid Statistics 
- [x] Mailbox Provider Comparison
- [x] Category Statistics
- [x] Device Statistics

Closes #

### CODE REVIEW

**Comment by wdharmana** [comment]
I added callout about email insight service. 🥇

**Comment by thinkingserious** [comment]
Hello @wdharmana,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by ksigler7** [comment]
@wdharmana - this is an awesome PR! Super clean, and GREAT content. Thanks so much!!!

**Comment by thinkingserious** [comment]
Hello @wdharmana,<br /><br/>Thanks again for the PR!<br /><br />                                         You have earned 16 out of the 5 points needed to receive glorious SendGrid Hacktoberfest swag.<br /><br />                                         Please take a moment to checkout <a href="https://dx.sendgrid.com/hacktoberfest/issues">this link</a> to find more issues to get you past the required threshold or to simply continue the celebration.<br /><br />                                         Also, <strong>please be sure you have officially registered with us <a href="https://dx.sendgrid.com/hacktoberfest/join">here</a> by November 1, 2018</strong> to qualify.<br /><br />                                         If you have any questions you can email us at <a href="mailto:dx+hacktoberfest2018@sendgrid.com">dx+hacktoberfest2018@sendgrid.com</a>.<br /><br />                                         Thank you and Happy Hacktobering!<br /><br />                                         Team SendGrid

**Comment by wdharmana** [comment]
> @wdharmana - this is an awesome PR! Super clean, and GREAT content. Thanks so much!!!

Thank you @ksigler7 ! I really enjoy contribute here and I hope i can continue my contribution next time.

**Comment by wdharmana** [comment]
> Hello @wdharmana,
> 
> Thanks again for the PR!
> 
> You have earned 16 out of the 5 points needed to receive glorious SendGrid Hacktoberfest swag.
> 
> Please take a moment to checkout [this link](https://dx.sendgrid.com/hacktoberfest/issues) to find more issues to get you past the required threshold or to simply continue the celebration.
> 
> Also, **please be sure you have officially registered with us [here](https://dx.sendgrid.com/hacktoberfest/join) by November 1, 2018** to qualify.
> 
> If you have any questions you can email us at [dx+hacktoberfest2018@sendgrid.com](mailto:dx+hacktoberfest2018@sendgrid.com).
> 
> Thank you and Happy Hacktobering!
> 
> Team SendGrid

@thinkingserious Cool!! Thanks. I've register and wait for cool swag from Sendgrid

**Pull request merged**
