### PR TITLE
Mako 3486 add asm groups to display

### PR DESCRIPTION
**Pull request by dmowcomber**

### CODE REVIEW

**Comment by robertacosta** [comment]
LGTM

**Comment by dmowcomber** [comment]
retest this please

**Comment by mbernier** [comment]
@dmowcomber @robertacosta  There was a build issue on docs causing the issue, I believe I have fixed it. It is rebuilding right now, if it's good we can push this live when you're ready.

**Comment by dmowcomber** [comment]
@mbernier thanks. were ready to merge this pr now

**Pull request merged**
