### PR TITLE
Add Node wrapper library

### PR DESCRIPTION
**Pull request by adamreisnz**

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @adamreisnz,<br /><br/>Thank you for the PR!<br />                                              <br />We will be reviewing this PR soon, in the mean                                              time, if you have not, please be sure to                                              <a href="https://github.com/sendgrid/docs#clas-and-cclas">                                             sign our CLA</a> so that we can merge your changes. Thanks again!                                             <br /><br />Team DX

**Comment by adamreisnz** [comment]
@thinkingserious I think I already signed the CLA earlier, so should be good to go.
I've just recently changed my Github username, so maybe that's why it's not finding it. It used to be @adambuczynski

**Comment by thinkingserious** [comment]
Hi  @adamreisnz,

I'm not sure if our CLAs have to be tied to a specific GitHub username. I will find out and let you know. 

Thanks for taking the time to add the link, and of course, for all of your support!

**Comment by thinkingserious** [comment]
@adamreisnz,

Unfortunately, I'm going to need a new CLA :(

Our CLAs are currently attached to GitHub usernames, because you may have different GitHub usernames attached to different organizations.

Apologies for the red tape and thanks again for the PR.

**Comment by adamreisnz** [comment]
@thinkingserious no problem, I've sent it through

**Pull request merged**
