### PR TITLE
Account Settings: Add Page - 'Verifying Your Account'

### LINKED ISSUE #3999: Adding account verification information to Account and Settings Documentation
Add the information from this FAQ page into a new "Verifying your Account" page. 

https://github.com/sendgrid/docs/blob/Whatthefoxsays-patch-15/source/Classroom/Basics/Account/account_sign_up_faq.md

Use the following format for the head matter of the page, adding your own title, SEO description, and keywords:

```
---
layout: page
weight: 0
group: account-management
title: 
seo:
  title: 
  description:
  keywords: 
navigation:
  show: true
---
```

### PR DESCRIPTION
**Pull request by duncanleung**
**Description of the change**:
Add Page: Verifying your Account

Navigation will be under: Home > Account And Settings > Verifying Your Account

**Reason for the change**:
Transferring content from FAQ: account_sign_up_faq 

https://github.com/sendgrid/docs/blob/Whatthefoxsays-patch-15/source/Classroom/Basics/Account/account_sign_up_faq.md

**Minor Update:**
I also saw that **domain whitelabel** is now called **domain authentication**, and linked to the corresponding domain authentication page:
http://localhost:8000/ui/account-and-settings/how-to-set-up-domain-authentication/

**Link to original source**:

Closes #3999

### CODE REVIEW

**Comment by ksigler7** [comment]
@duncanleung - this is awesome!!! We'll take a closer look at it today and get it merged in

**Comment by thinkingserious** [comment]
Hello @duncanleung,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by duncanleung** [comment]
Hi @ksigler7 just pinging this PR =)

I see there's a flood of PRs coming for Hacktoberfest so I can understand it's getting busy!

Thanks again! =)

**Comment by Whatthefoxsays** [comment]
This was a great start @duncanleung! I just edited the content a little bit to make it fit our style/voice. We appreciate all of your help!

**Comment by duncanleung** [comment]
@Whatthefoxsays Great, thanks for the edits!

**Pull request merged**
