### PR TITLE
Updated Laravel Framework Integration Documentation

### PR DESCRIPTION
**Pull request by Braunson**
Updated Laravel Framework Integration for Laravel 5.5 LTS! Reference issue #2875

**Description of the change**: Document changes
**Reason for the change**: Issue request
**Link to original source**: https://github.com/sendgrid/docs/issues/2875

@ksigler7

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3035) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3035) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/docs?pullRequest=3035) it.</sub>

**Comment by Braunson** [comment]
I've previously signed it? Why's the status still pending?

**Comment by ksigler7** [comment]
@Braunson thanks so much for these updates!

**Comment by thinkingserious** [comment]
Hello @Braunson,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/announcing-hacktoberfest-2017">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
