### PR TITLE
Updates for Heroku

### PR DESCRIPTION
**Pull request by emilythrasher**
# Fixes # 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [ ] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
- 
- 

If you have questions, please send an email to [Sendgrid](mailto:docs@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3296) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3296) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/docs?pullRequest=3296) it.</sub>

**Comment by emilythrasher** [comment]
For some reason I can't find patch-1 under branches, so I can't upload the 4 files that I referenced in my last commit the way that Kaylyn showed me too:


herokupw1
herokupw2
herokupw3
herokupw4

**Comment by ksigler7** [comment]
@emilythrasher - you are not the only one having this issue right now! We think github itself is having issues. I'll let you know when things seem like they're back up!

**Comment by ksigler7** [comment]
@emilythrasher - okay - everything looks like it's working again! Want to try again?

**Comment by ksigler7** [comment]
@emilythrasher - this is awesome!! thanks so much for this. I'm going to go ahead and merge this, but do you mind still signing the CLA - it's not technically required, but it saves us a lot of work.

**Comment by thinkingserious** [comment]
Hello @emilythrasher,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
