### PR TITLE
Fix spelling and apply style guidelines

### PR DESCRIPTION
**Pull request by hugovk**
**Description of the change**:

* Fix general spelling mistakes
* Fix SendGrid typos
* Fix GitHub typos
* Apply some style guidelines (including to the style guide itself :)

**Reason for the change**:

It's easier to read and looks better and is more consistent.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3993) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3993) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/docs?pullRequest=3993) it.</sub>

**Comment by ksigler7** [comment]
woah @hugovk!!! thanks for this!

**Comment by ksigler7** [comment]
can you please sign our CLA?

**Comment by hugovk** [comment]
You're welcome! CLA already signed.

**Comment by ksigler7** [comment]
@hugovk - thanks for the offer of splitting it out! we just got a little behind this week - merging this very soon!

**Comment by ksigler7** [comment]
@hugovk - did you do this all by hand, or do you have some sort of script you used?

**Comment by thinkingserious** [comment]
Hello @hugovk,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by hugovk** [comment]
@ksigler7 For the spelling, I used [codespell](https://github.com/codespell-project/codespell) to identify and help fix. I used it like:

```
codespell ---quiet-level 2 --interactive 3 --write-changes
```
Where: the `2` is to disable warnings about binary files, and `3` is to be asked for confirmation, and to choose the fix when more than one is available.

The typos and style guide were applied by hand, and using PyCharm's to search for a certain thing in all files.

**Comment by ksigler7** [comment]
@hugovk - thanks for sharing your process!!

**Comment by hugovk** [comment]
You're welcome! Codespell is useful because it searches for common misspellings in code, rather than searching for all sorts of misspellings (say, like MS Word), which for code tends to turn up lots of false positives.

**Pull request merged**
