### PR TITLE
Fixed typo in parse.apiblueprint

### PR DESCRIPTION
**Pull request by ctrimm**
Fixed typo in parse.apiblueprint file.
[Original Source](https://github.com/sendgrid/docs/blob/develop/source/API_Reference/Web_API_v3/Webhooks/parse.apiblueprint#L12)

@ksigler7

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/docs?pullRequest=2761) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/docs?pullRequest=2761) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/docs?pullRequest=2761) it.</sub>

**Comment by ksigler7** [comment]
@ctrimm good catch and thanks for the fix!

**Comment by thinkingserious** [comment]
Hello @ctrimm,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by ctrimm** [comment]
No problem @ksigler7 & @thinkingserious. I may try to tackle a few more of the open issues sometime in the near future. Thanks for the swag!

**Pull request merged**
