### PR TITLE
Add Elixir Bamboo project

### PR DESCRIPTION
**Pull request by pinx**

### CODE REVIEW

**Comment by eschallock** [comment]
Hello @pinx! Thanks for the PR! We've recently started asking contributors to our Docs to fill out a [CLA](https://github.com/sendgrid/docs#clas-and-cclas) before we merge in pull requests. Would you be willing to send us a completed CLA for this change?

Thanks!

**Comment by pinx** [comment]
I have no relation with Bamboo. You better ask them directly.

**Comment by eschallock** [comment]
Hey @pinx - we actually only need a CLA from the individual making the change to our Documentation, which in this case would be you.

Please let us know if you have any questions.

**Comment by pinx** [comment]
Hi Eric,

Maybe it's because I'm European, but this seems like a ridiculous amount of
paperwork for contributing one line of documentation.

Feel free to copy/paste from my pull request, and enter it as your own IP
into the documentation. I don't need any credits or rights to my
contribution.

Best regards,

Marcel van Pinxteren
--------------------------

2016-10-10 21:23 GMT+02:00 Eric Schallock <notifications@github.com>:

**Pull request closed without merging**
