### PR TITLE
Rename node.js classroom page and update link to v3

### PR DESCRIPTION
**Pull request by PyroclasticMayhem**
**Description of the change**: Rename node.js classroom page and update link to v3
**Reason for the change**: Issue #2744
**Link to original source**:

@ksigler7

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/docs?pullRequest=2948) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/docs?pullRequest=2948) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/docs?pullRequest=2948) it.</sub>

**Comment by ksigler7** [comment]
Hey @PyroclasticMayhem,

Thanks for the updates! We're not really looking for this type of change right now. However, if you're participating in Hacktoberfest, please check out our issues: https://github.com/sendgrid/docs/issues - We have a bunch of pretty easy changes in there that we are looking for.

Thanks!
SendGrid Docs team

**Comment by ksigler7** [comment]
@PyroclasticMayhem, please ignore my other comment, I mixed this up with another one, and I see now that this is based on one of our open issues.

Thanks so much for the update and sorry for the confusion!

**Comment by thinkingserious** [comment]
Hello @PyroclasticMayhem,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
