### PR TITLE
chore: changes to make code consistent

### PR DESCRIPTION
**Pull request by KirankumarAmbati**
**Description of the change:**
Code Formatting
Converted stateful components to Functional components.

**Reason for the change:**
React 16.6 was just released, introducing React.memo. Quoting from the Motivation section of the RFC:

> Today in React, function components and PureComponent provide two different kinds of optimizations that can't be unified.
> 
> Function components let us avoid constructing a class instance. This benefits the initial render. Function components also tend to minify better than classes, which helps reduce the bundle size.
> 
> ⋮
> 
> By having memo as a first-class API in React itself, we can remove the need to make a choice between these optimizations. It makes it easy to memoize the output of function components without introducing other extra costs.

Now by using React.memo(), functional components can be optimized.

### CODE REVIEW

**Comment by KirankumarAmbati** [comment]
Hi @justinwhall,

Fixed some of the lint errors. They are some more errors that are not introduced by me. I'll try to fix them in another PR. Thanks !

**Comment by KirankumarAmbati** [comment]
**CC:** @ksigler7

**Comment by thinkingserious** [comment]
Hello @KirankumarAmbati,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by KirankumarAmbati** [comment]
Hi Team, are we good with this PR ? Or any more changes are required ?

**Comment by ksigler7** [comment]
@KirankumarAmbati - we got a ton of PRs that need review with the final Hacktoberfest push and we are still reviewing! Will let you know soon - thanks for touching base

**Comment by KirankumarAmbati** [comment]
Ya. I understand ! @ksigler7 

Take your time. No worries ! I just thought I could help you in some way. 🙂

**Comment by justinwhall** [comment]
Hi @KirankumarAmbati - We are still seeing some linting errors. One example is [here](https://github.com/sendgrid/docs/pull/4549/files#diff-5d0d123879ae5ca550d946484fc8b956R7).

Be sure you have eslint enabled. Thanks!

**Pull request closed without merging**
