### PR TITLE
Solving #3722

### LINKED ISSUE #3722: Missing event webhook `url_offset`
## Expected content

The new event webhook page is missing a description and example of `url_offset` that existed in the old event webhook page.

Here's the info from the old page:

```
{% anchor h3 %}
Click
{% endanchor %}

<table class="table table-bordered table-striped">
   <thead>
      <tr>
         <th>event</th>
         <th>email</th>
         <th>url</th>
         <th>category</th>
      </tr>
   </thead>
   <tbody>
      <tr>
         <td>click</td>
         <td>Message recipient</td>
         <td>URL Clicked</td>
         <td>The category you assigned</td>
      </tr>
   </tbody>
</table>

{% info %}
`url_offset` gives you more information about the link that was clicked. Links are indexed beginning at 0. `index` indicates which link was clicked based on that index. The type of link can be either text, HTML, or a header. `type` indicates the type of the link that was clicked.
{% endinfo %}

{% codeblock lang:json %}
{
  "sg_event_id":"sendgrid_internal_event_id",
  "sg_message_id":"sendgrid_internal_message_id",
  "ip":"255.255.255.255",
  "useragent":"Mozilla/5.0 (iPhone; CPU iPhone OS 7_1_2 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Version/7.0 Mobile/11D257 Safari/9537.53",
  "event":"click",
  "email":"email@example.com",
  "timestamp":1249948800,
  "url":"http://yourdomain.com/blog/news.html",
  "url_offset": {
    "index": 0,
    "type": "html"
  },
  "unique_arg_key":"unique_arg_value",
  "category":["category1", "category2"],
  "newsletter": {
    "newsletter_user_list_id": "10557865",
    "newsletter_id": "1943530",
    "newsletter_send_id": "2308608"
  },
  "asm_group_id": 1
}
{% endcodeblock %}
```

## Actual content

Add the note and the example back in.

**Link to page**: https://sendgrid.com/docs/API_Reference/Event_Webhook/event.html

### PR DESCRIPTION
**Pull request by KayDee**
**Description of the change**:
Added example of ```url_offset```
**Reason for the change**:
Was an open issue
**Link to original source**:

Closes #3722

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @KayDee,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by ksigler7** [comment]
@KayDee - sorry about this, I am closing it because it did get solved after the directory structure was changed, but since you did it first I am still giving you the hacktoberfest credit (with us and Digital Ocean)

**Comment by thinkingserious** [comment]
Hello @KayDee,<br /><br/>Thanks again for the PR!<br /><br />                                         We noticed that you have earned 1 out of the 5 points needed to receive glorious SendGrid Hacktoberfest swag.<br /><br />                                         Please take a moment to checkout <a href="https://dx.sendgrid.com/hacktoberfest/issues">this link</a> to find more issues to get you past the required threshold.<br /><br />                                         Also, please be sure that you have officially registered <a href="https://dx.sendgrid.com/hacktoberfest/join">here</a>.<br /><br />                                         Thank you and Happy Hacktobering!<br /><br />                                         Team SendGrid DX

**Comment by KayDee** [comment]
Hi @thinkingserious 
I wanted to do more, but your PR section has been very busy to leave any issue unattended.
I registered on the link, and if i qualify for something with 1 credit, it'd be cool. Otherwise, no worry.

**Comment by thinkingserious** [comment]
Hello @KayDee,<br /><br/>Thanks again for the PR!<br /><br />                                         You have earned 1 out of the 5 points needed to receive glorious SendGrid Hacktoberfest swag.<br /><br />                                         Please take a moment to checkout <a href="https://dx.sendgrid.com/hacktoberfest/issues">this link</a> to find more issues to get you past the required threshold or to simply continue the celebration.<br /><br />                                         Also, <strong>please be sure you have officially registered with us <a href="https://dx.sendgrid.com/hacktoberfest/join">here</a> by November 1, 2018</strong> to qualify.<br /><br />                                         If you have any questions you can email us at <a href="mailto:dx+hacktoberfest2018@sendgrid.com">dx+hacktoberfest2018@sendgrid.com</a>.<br /><br />                                         Thank you and Happy Hacktobering!<br /><br />                                         Team SendGrid

**Pull request closed without merging**
