### PR TITLE
Remove Bower

### PR DESCRIPTION
**Pull request by tulikavijay**
# Fixes # 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
- solves issues [:#3302](https://github.com/sendgrid/docs/issues/3302)

If you have questions, please send an email to [Sendgrid](mailto:docs@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by ksigler7** [comment]
@tulikavijay - Thanks so much for your effort on this! There was a conflict with the latest version of our main develop branch and now that I have it merged, the Travis build is failing. Do you mind taking a look at it? I can't figure out what the issue is, though I do have some more ideas I can test.

**Comment by tulikavijay** [comment]
I have my semester exams this November. So I'll check it out in awhile if that's ok.

**Comment by ksigler7** [comment]
@tulikavijay - fair enough! We'll keep troubleshooting it too

**Comment by cmckni3** [comment]
Looks like it's trying to `git clone` Bootstrap and it's failing due to using ssh. I'm not sure why the `@bower_components` organization is being used for some of the packages. Some of them exist as normal packages.

**Comment by ksigler7** [comment]
closing this since it's more than 90 days old and we haven't been able to fix it. let me know if someone has fix for this though!

**Pull request closed without merging**
