### PR TITLE
updated ngrok docs

### PR DESCRIPTION
**Pull request by nquinlan**
ngrok has made some updates to its command line tool. I changed the syntax in the article to reflect it.

### CODE REVIEW

**Comment by eschallock** [comment]
Hello @nquinlan! Thanks for the PR! We've recently started asking contributors to our Docs to fill out a [CLA](https://github.com/sendgrid/docs#clas-and-cclas) before we merge in pull requests. Would you be willing to send us a completed CLA for this change?

Thanks!

**Comment by nquinlan** [comment]
Can't easily do from mobile. You're welcome to use any of my code in this repo pursuant to the license or contracts I had in place with SendGrid.

**Comment by eschallock** [comment]
@nquinlan Sadly, I've been told I still need that CLA. If you have time to fill one out and send it our way, I'd be happy to get this PR merged in and live on the Docs. I apologize for the hassle!

**Comment by eschallock** [comment]
@nquinlan Sorry to push on this yet again, but if you'd like me to merge this in, would you be able to submit a completed [CLA](https://github.com/sendgrid/docs#clas-and-cclas)? I apologize for the extra paper work, and we are working to make this process smoother.

Alternatively, if you don't mind giving up your credit for the change, I can close this PR and make the same change from my account. I know this might seem silly for a small change.

**Comment by ksigler7** [comment]
Hey @nquinlan, thanks so much for your contribution! Unfortunately, since you haven't signed our CLI, we're not going to be able to merge this pull request at this time.  Since this has been sitting here a while, I am going to go ahead and close this pull request, but feel free to open it again in the future if you sign the CLI!

**Pull request closed without merging**
