### PR TITLE
Updates as requested by @ksigler7 for Table of Contents

### PR DESCRIPTION
**Pull request by saideepd**
**Description of the change**: Added Table of Contents to **dashboard.md** file
**Reason for the change**: Didn't exist before and was mentioned in Issues
**Link to original source**: https://github.com/sendgrid/docs/blob/develop/source/User_Guide/dashboard.md

Closes #3110 

**Description of the change**: Added Table of Contents to **email_activity.md** file
**Reason for the change**: Didn't exist before and was mentioned in Issues
**Link to original source**: https://github.com/sendgrid/docs/blob/develop/source/User_Guide/email_activity.md

Closes #3111 

**Description of the change**: Added Table of Contents to **about.md** file
**Reason for the change**: Didn't exist before and was mentioned in Issues
**Link to original source**: https://github.com/sendgrid/docs/blob/develop/source/User_Guide/about.md

Closes #3114 

@ksigler7

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3139) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3139) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/docs?pullRequest=3139) it.</sub>

**Comment by saideepd** [comment]
@ksigler7 Can you please tell me what exactly is conflicting in above mentioned files? I did make changes after seeing this conflicting message. But, still the issue exists.

**Comment by ksigler7** [comment]
hey @saideepd - thanks so much for your effort on this!

In your [original comment](https://github.com/sendgrid/docs/pull/3139#issue-267180857) on this pull request, you cite several other pull requests (Closes #3114 , Closes #3111, and Closes #3110).

These pull requests that you cited were not issues, but actual changes to content in order to solve and issue (#3088)

So the reason why there are conflicts to your files is because you made the same exact changes as the other people did in their pull requests. So the conflicts were caused when the other users changes got merged in.

Since your changes are a duplicate of what has already been fixed, I am going to go ahead and close this pull request - *however!* issue #3088 is not yet complete! even though people have made pull requests against it, it's partially complete - there are other tables of contents that need to be added in the user guide

**Comment by saideepd** [comment]
@ksigler7 Thanks a lot for clearing the confusion

**Pull request closed without merging**
