### PR TITLE
Updated '2013-2017' License from the Old one.

### PR DESCRIPTION
**Pull request by ssiddhantsharma**
**Description of the change**:
**Reason for the change**:
**Link to original source**:

Closes #

@ksigler7
****

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3261) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3261) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/docs?pullRequest=3261) it.</sub>

**Comment by ksigler7** [comment]
wow, good catch!

**Comment by thinkingserious** [comment]
Hello @ssiddhantsharma,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/announcing-hacktoberfest-2017">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by ssiddhantsharma** [comment]
Team,
I have already filled the form because my earlier PR was accepted.
So do I need to fill an another one?

I have already filled one regarding the swag you are providing for
HacktoberFest.

**Comment by ksigler7** [comment]
@ssiddhantsharma - thanks for asking! No, you don't need to fill out a new one.

**Pull request merged**
