### PR TITLE
Fix spacing, typo, and markup in create_edit.md

### LINKED ISSUE #3208: Fix typos in transactional template documentation
## To do:

Fix typos and broken markdown on [this page](https://sendgrid.com/docs/User_Guide/Transactional_Templates/create_edit.html).

### PR DESCRIPTION
**Pull request by akoliyot**
**Description of the change**: Fixed typos, markup, and word spacing. 
**Reason for the change**: Issue asking to "Fix typos in transactional template documentation".
**Link to original source**: https://github.com/sendgrid/docs/blob/develop/source/User_Guide/Transactional_Templates/create_edit.md

Closes #3208

@ksigler7

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3225) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3225) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/docs?pullRequest=3225) it.</sub>

**Comment by akoliyot** [comment]
@ksigler7 I did find 2 more places where it might need fixing: 

1. your customers to start receiving, you’ll need to make that Version “Active.”
Should the 'Version' here be 'version'?

2. Many non-technical customers will hire a front end or email template developer to build their templates.
Should 'front end' be 'front-end'?

I did not make these changes since I wasn't sure if it needed to be fixed.

**Comment by ksigler7** [comment]
@akoliyot - thanks for your effort here! To answer your questions:
1. Yes, it should be 'version'.
1. Yes, 'front-end' is correct.

Do you want to go ahead and update in this pull request?

**Comment by akoliyot** [comment]
@ksigler7 Thank you :) I made the changes.

**Comment by thinkingserious** [comment]
Hello @akoliyot,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by ksigler7** [comment]
thanks @akoliyot!!

**Pull request merged**
