### PR TITLE
Added volumes to Dockerfile

### LINKED ISSUE #3239: Update docker build to use docker-compose and volumes
As of #3236 we have the docs environment running in docker. This is AMAZING! However, each change to a file means you have to rebuild the docker container and the build files are not necessarily being cached. 

## Expected Result
What would be amazing is:
- docker container setup that mounts a local volume for:
  - node_modules  -- allowing for caching on build
  - ruby gems  -- allowing for caching on build
  - /source/ folder
  - /public/ folder

### PR DESCRIPTION
**Pull request by xR86**
# Fixes # 
Fixes #3239

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
- adds volumes for the specified folders and speeds up the build process

If you have questions, please send an email to [Sendgrid](mailto:docs@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3301) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3301) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/docs?pullRequest=3301) it.</sub>

**Comment by ksigler7** [comment]
hi @xR86 - thanks so much for this update! We are in the process of testing it, which may take a few days, as we have gotten a ton of Hacktoberfest traffic. Don't worry though, we will make sure to count it toward Hacktoberfest when it does get merged in!

**Comment by thinkingserious** [comment]
Hello @xR86,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by xR86** [comment]
Hello @thinkingserious,
Thanks !
I've tried to complete the form, but I got this: `I don't know who you are; I should, but regretfully I don't.`
I'll probably be better off just to send you an email with this ?

**Comment by ksigler7** [comment]
@xR86 - sorry you ran into this issue! we had so many people requesting swag last night that we were having issues with out request form. Can you please try clearing your cache and then retry the form now? We think we have the issues ironed out, but let us know on here if you're still running into issues.

**Comment by xR86** [comment]
@ksigler7 Form works now. Didn't get an email confirmation, but it should be good. Thanks !

**Pull request merged**
