### PR TITLE
Update your_reputation_what_is_it.md

### PR DESCRIPTION
**Pull request by bhammerquist**
Minor verbiage change. Removed the word "necessarily".

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @bhammerquist,<br /><br/>Thank you for the PR!<br />                                              <br />We will be reviewing this PR soon, in the mean                                              time, if you have not, please be sure to                                              <a href="https://github.com/sendgrid/docs#clas-and-cclas">                                             sign our CLA</a> so that we can merge your changes. Thanks again!                                             <br /><br />Team DX

**Comment by ksigler7** [comment]
Hey @bhammerquist , thanks so much for your contribution! Unfortunately, since you haven't signed our CLI, we're not going to be able to merge this pull request at this time.  Since this has been sitting here a while, I am going to go ahead and close this pull request, but feel free to open it again in the future if you sign the CLI!

**Comment by thinkingserious** [comment]
Hello @bhammerquist,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/docs?pullRequest=2562) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/docs?pullRequest=2562) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/docs?pullRequest=2562) it.</sub>

**Pull request merged**
