### PR TITLE
Added glossary page for the term "preheader"

### PR DESCRIPTION
**Pull request by Logan1x**
**Description of the change**: Added glossary page for the term "preheader"
**Reason for the change**: issue #2839 
**Link to original source**:

@ksigler7

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/docs?pullRequest=2947) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/docs?pullRequest=2947) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/docs?pullRequest=2947) it.</sub>

**Comment by thinkingserious** [comment]
Hello @Logan1x,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by ksigler7** [comment]
thanks so much @Logan1x!

**Comment by Logan1x** [comment]
Thank you so much for giving me opportunity 😊 @ksigler7 @SendGridDX @thinkingserious

**Pull request merged**
