### PR TITLE
Update to teammates documentation #4110

### LINKED ISSUE #4110: Update to teammates documentation
## Expected content

In teammates, we need to add a note to line 14 like this:

```
<call-out>

Free and Essentials customers can create 1 teammate per account, and Pro customers or higher packages up to 1000 teammates. 

</call-out>
```

**Link to page**: https://sendgrid.com/docs/ui/account-and-settings/teammates/

### PR DESCRIPTION
**Pull request by abdullah-K**
**Description of the change**: Add a note specifying the number of team-mates that can be added by different customer types.
**Reason for the change**: Issue #4110 opened by @ksigler7 

Closes #4110

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/docs?pullRequest=4118) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/docs?pullRequest=4118) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/docs?pullRequest=4118) it.</sub>

**Comment by ksigler7** [comment]
thanks @abdullah-K - please go ahead and sign the CLA when you get a moment!

**Comment by abdullah-K** [comment]
@ksigler7 Just signed it :smile:

**Comment by thinkingserious** [comment]
Hello @abdullah-K,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
