### PR TITLE
deleting 2 pages and redirect them

### PR DESCRIPTION
**Pull request by PAPERPANKS**
**Description of the change**: deleting [dashboard.md](https://github.com/sendgrid/docs/blob/develop/source/User_Guide/dashboard.md) and [about.md](https://github.com/sendgrid/docs/blob/develop/source/User_Guide/about.md) file
**Reason for the change**: as mentioned in issue #3209 
**Link to original source**: [here](https://github.com/PAPERPANKS/docs/blob/develop/source/_redirects.htaccess)

closes issue #3209 

@ksigler7

### CODE REVIEW

**Comment by PAPERPANKS** [comment]
Check code for redirection of links [here](https://github.com/PAPERPANKS/docs/blob/develop/source/_redirects.htaccess)

**Comment by PAPERPANKS** [comment]
@ksigler7 if this commit resolve this issue, then merge this asap as the deadline for the hacktoberfest is very near

**Comment by thinkingserious** [comment]
Hello @PAPERPANKS,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/announcing-hacktoberfest-2017">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by PAPERPANKS** [comment]
can you add the `difficulty `label

**Comment by ksigler7** [comment]
@PAPERPANKS - yes, fixed!

**Comment by ksigler7** [comment]
@PAPERPANKS - yes! I will dig in to see what happened and followup with you by email

**Pull request merged**
