### PR TITLE
CONTRIBUTING.md : Add file

### PR DESCRIPTION
**Pull request by prnvdixit**
Add CONTRIBUTING.md to the docs repo.

Closes https://github.com/sendgrid/docs/issues/4294

**Description of the change**:
**Reason for the change**:
**Link to original source**:

Closes #

### CODE REVIEW

**Comment by prnvdixit** [comment]
Accomodating changes mentioned in @ksigler7's [comment](https://github.com/sendgrid/docs/pull/4313#issuecomment-431536744) :smile:

**Comment by ksigler7** [comment]
@prnvdixit - thank you for doing this! Do you mind updating the setup steps to match the steps found in the readme? This is a version for the old repo, and those steps don't match this repo.

**Comment by prnvdixit** [comment]
@ksigler7 Sure I will do so - Busy for a few days :sweat_smile:

**Comment by prnvdixit** [comment]
Hey @ksigler7 - Thanks for the heads up! I literally forgot about this one :smile:.. Sending the updates in a bit.

By the way, Hacktoberfest reminds me - I haven't got my Tee from last year even yet :stuck_out_tongue:

**Comment by thinkingserious** [comment]
Hello @prnvdixit,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by ksigler7** [comment]
@prnvdixit - thanks for the updates! I've gone ahead and given you the hacktoberfest credit, and I'll do an in-depth review on this later today! 

Sorry to hear that you never received a t-shirt last year. We've really improved the process for this year and it should be much more streamlined. One recommendation I would make is to have them send the swag to a business address if you can. Last year we had a huge problem with the shirts making it to peoples personal addresses.

**Comment by prnvdixit** [comment]
@ksigler7 Yeah... Sure. Tell me if there is anything else that needs to be done, I'll make the required updates :smile:

Thanks for the tip - I gave my university address now, hope it reaches me this time. :sweat_smile:.
By the way, I forgot to mention - Last year *somehow* I got a thank you tweet from SendGrid... Thanks for that :smile:

**Comment by thinkingserious** [comment]
Hello @prnvdixit,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Comment by prnvdixit** [comment]
Hey! I haven't received any communication yet (not even asking for address). I'm hoping that I'm not missing out on this again this year :sweat_smile:

**Pull request merged**
