### PR TITLE
Add documentation for v3 statistics APIs.

### PR DESCRIPTION
**Pull request by mauidude**

### CODE REVIEW

**Comment by mbernier** [comment]
Q1: Are we planning on having more than one entry in the Categories directory? 

If not, please move categories.md up a directory to be ```source/API_Reference/Web_API_v3/categories.md```

Q2: Do any of these deprecate or effectively replace/improve another piece of functionality that we have documented elsewhere? (e.g. Parse) If so, please let me know so that I can go through and add warnings to the tops of those pages or on those endpoints to say "go here instead".

- Notifying @eddiezane so he knows these are coming for the library code. 

Thanks!!

**Comment by mauidude** [comment]
1. Yea I would think at some point there would be the full CRUD set of endpoints for managing categories but I'm not sure when that would happen.

2. This is going to be replacing our existing stats APIs located here: 
- https://sendgrid.com/docs/API_Reference/Web_API/Statistics/index.html
- https://sendgrid.com/docs/API_Reference/Web_API/Statistics/statistics_advanced.html

**Comment by elbuo8** [comment]
Thanks for contributing to SendGrid Open Source! We think it's awesome when community members contribute to our projects and want to celebrate that.

The following link will ask you to authenticate with Github (so we can verify your identity), it will then ask for a little bit more information and we'll then send you a thanks for contributing.

**[Click Here to Continue »](http://contribot.com/auth)**

Once again, thank you!

**Comment by mbernier** [comment]
Thanks @mauidude - these are merged in and will be live soon

**Pull request merged**
