### PR TITLE
Laravel example is not working correctly #3559

### LINKED ISSUE #3559: Laravel example is not working correctly
I am implementing sendgrid with Laravel so I leverage from your example, but so far I had to make 2 fixes for making it work:

In file `app/Mail/TestEmail.php`

**1. How to access data**
You cannot access to `->with([ 'message' => $data['message'] ]);` from inside build() because it's a public attribute so it should be changed to `->with(['message' => $this->data['message']]);`

**2. You cannot use the key "message" along _with_ method**
In somehow Laravel defines "message" key as a object when is received in the view. In the same line as point 1 I had to change `->with(['message' => $this->data['message']]);` for `->with(['greeting' => $this->data['message']]);`.

So I could finally display the value on my view like it:
```
<!DOCTYPE html>
<html lang="en-US">
<head>
    <meta charset="utf-8">
</head>
<body>
<h2>{{$greeting}}</h2>
<p></p>
</body>
</html>
```

https://sendgrid.com/docs/Integrate/Frameworks/laravel.html

Tested on Laravel 5.6
Greetings!

### PR DESCRIPTION
**Pull request by cferrante**
HUGE fan of SendGrid and Laravel 5.6!
Noticed recommended change was not implemented.

**Description of the change**:
**Reason for the change**:
**Link to original source**:

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3714) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/docs?pullRequest=3714) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/docs?pullRequest=3714) it.</sub>

**Comment by cferrante** [comment]
NewB etiquette apologies (any guidance welcomed)...I believe someone has proposed to accept these changes "if we could use the template from the styleguide for consistency"...

If that is true, and I'm following this process correctly, my understanding is that the user who originally reported this issue, recommended 2 changes: 

1) $data to $this->data in two spots. This is indeed a compile issue, so would be a required change for 100% correctness. 

2) Request to change the test.blade.php file in order to make the data dynamic, rather than hard-coded. Although helpful for Laravel users, might be considered an enhancement rather than an issue fix?

If someone would point me to the "template from the styleguide", perhaps I can confirm my understanding is correct, so that I can provide feedback in order for someone to close a ticket.

**Comment by ksigler7** [comment]
@cferrante thank you so much for picking this up! This looks good to me and for sure fixes the first part of #3559 - I am comfortable merging this in as you have it here.

I can't find a reference to someone sending you to the style guide so I have no idea where to point you - can you more specifically point me to where someone said that?

I guess the second part of #3559 could be considered a enhancement request, but in this case it really does seem to improve the experience, so we are good updating it as a part of this issue.

**Comment by cferrante** [comment]
Well, I'm a little embarrassed, because as such a NewB, I'm probably misunderstanding something. At the end of your comment, there is a screen that looks like so...
image
At the "Review required" item, there is a hyperlink "Learn more". I clicked it, read the content, and reviewed the images, but could not reconcile it back to this page. 

I believe what I did was mistake the image there for something specific to this case - my mistake.

Is there anything further I should do to help facilitate closing of the case?

**Comment by ksigler7** [comment]
don't be embarrassed! I see what you mean now - that just means that someone (usually one of us maintainers, but sometimes someone in the community) need to review it and approve it before it can be merged into our repo. Some repos do not have this in place, but you'll find that all of the SendGrid repos do.

**Comment by thinkingserious** [comment]
Hello @cferrante,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
